# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\PC\Desktop\python-thang (2)\QTThread\sep_web_Gpm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1499, 925)
        self.verticalLayoutWidget = QtWidgets.QWidget(Widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-10, 0, 1511, 701))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.startBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.startBtn.setStyleSheet("#startBtn {\n"
"    background-color: white;       /* nền trắng */\n"
"    color: black;                  /* chữ đen */\n"
"    border: 2px solid black;       /* viền đen đậm */\n"
"    border-radius: 5px;            /* bo góc mềm mại */\n"
"    font: 800 12pt \"Segoe UI\";     /* font Segoe UI, đậm, 10pt */\n"
"    font-weight: bold;             /* đảm bảo đậm rõ */\n"
"}\n"
"\n"
"#startBtn:hover {\n"
"    background-color: #f0f0f0;     /* nền xám nhạt khi hover */\n"
"    border: 2px solid black;       /* giữ viền đen */\n"
"    color: black;                  /* chữ vẫn đen */\n"
"}\n"
"")
        self.startBtn.setObjectName("startBtn")
        self.verticalLayout.addWidget(self.startBtn)
        self.stopBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.stopBtn.setStyleSheet("#stopBtn {\n"
"    background-color: white;       /* nền trắng */\n"
"    color: black;                  /* chữ đen */\n"
"    border: 2px solid black;       /* viền đen đậm */\n"
"    border-radius: 5px;            /* bo góc mềm mại */\n"
"    font: 800 12pt \"Segoe UI\";     /* font Segoe UI, đậm, 10pt */\n"
"    font-weight: bold;             /* đảm bảo đậm rõ */\n"
"}\n"
"\n"
"#stopBtn:hover {\n"
"    background-color: #f0f0f0;     /* nền xám nhạt khi hover */\n"
"    border: 2px solid black;       /* giữ viền đen */\n"
"    color: black;                  /* chữ vẫn đen */\n"
"}\n"
"")
        self.stopBtn.setObjectName("stopBtn")
        self.verticalLayout.addWidget(self.stopBtn)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Widget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(250, 750, 381, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_2.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 700 9pt \"Segoe UI\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 700 9pt \"Segoe UI\";")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 700 9pt \"Segoe UI\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Widget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(60, 750, 191, 171))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_10.setStyleSheet("font: 700 9pt \"Segoe UI\";\n"
"background-color: rgb(0, 170, 255);")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_3.addWidget(self.lineEdit_10)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_12.setStyleSheet("font: 700 9pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 0);")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.verticalLayout_3.addWidget(self.lineEdit_12)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_11.setStyleSheet("font: 700 9pt \"Segoe UI\";\n"
"background-color: rgb(255, 0, 0);")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout_3.addWidget(self.lineEdit_11)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Widget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(840, 750, 191, 171))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_14.setStyleSheet("font: 700 9pt \"Segoe UI\";\n"
"background-color: rgb(0, 255, 0);")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.verticalLayout_4.addWidget(self.lineEdit_14)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_15.setStyleSheet("font: 700 9pt \"Segoe UI\";\n"
"background-color: rgb(255, 170, 0);")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.verticalLayout_4.addWidget(self.lineEdit_15)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_17.setStyleSheet("font: 700 9pt \"Segoe UI\";\n"
"\n"
"background-color: rgb(170, 85, 255);")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.verticalLayout_4.addWidget(self.lineEdit_17)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(Widget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(1030, 750, 381, 171))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lineEdit_13.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 700 9pt \"Segoe UI\";")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.verticalLayout_5.addWidget(self.lineEdit_13)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lineEdit_16.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"font: 700 9pt \"Segoe UI\";")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.verticalLayout_5.addWidget(self.lineEdit_16)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lineEdit_18.setStyleSheet("background-color: rgb(170, 85, 255);\n"
"\n"
"font: 700 9pt \"Segoe UI\";")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.verticalLayout_5.addWidget(self.lineEdit_18)
        self.comboBox = QtWidgets.QComboBox(Widget)
        self.comboBox.setGeometry(QtCore.QRect(248, 730, 381, 26))
        self.comboBox.setStyleSheet("\n"
"font: 700 9pt \"Segoe UI\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_5 = QtWidgets.QLineEdit(Widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(60, 730, 191, 26))
        self.lineEdit_5.setStyleSheet("font: 700 9pt \"Segoe UI\";")
        self.lineEdit_5.setObjectName("lineEdit_5")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Widget", "Proxy"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Widget", "Email"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Widget", "Mật khẩu"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Widget", "Tháng sinh nhật"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Widget", "Trạng Thái"))
        self.startBtn.setText(_translate("Widget", "Bắt đầu"))
        self.stopBtn.setText(_translate("Widget", "Dừng"))
        self.lineEdit_10.setText(_translate("Widget", "Mail Domain"))
        self.lineEdit_12.setText(_translate("Widget", "Mật Khẩu"))
        self.lineEdit_11.setText(_translate("Widget", "Số Luồng"))
        self.lineEdit_14.setText(_translate("Widget", "Phiên Bản Trình Duyệt"))
        self.lineEdit_15.setText(_translate("Widget", "Phiên bản tool"))
        self.lineEdit_17.setText(_translate("Widget", "Danh Sách Proxy"))
        self.comboBox.setItemText(0, _translate("Widget", "Jan"))
        self.comboBox.setItemText(1, _translate("Widget", "Feb"))
        self.comboBox.setItemText(2, _translate("Widget", "Mar"))
        self.comboBox.setItemText(3, _translate("Widget", "Apr"))
        self.comboBox.setItemText(4, _translate("Widget", "May"))
        self.comboBox.setItemText(5, _translate("Widget", "Jun"))
        self.comboBox.setItemText(6, _translate("Widget", "Jul"))
        self.comboBox.setItemText(7, _translate("Widget", "Aug"))
        self.comboBox.setItemText(8, _translate("Widget", "Sep"))
        self.comboBox.setItemText(9, _translate("Widget", "Oct"))
        self.comboBox.setItemText(10, _translate("Widget", "Nov"))
        self.comboBox.setItemText(11, _translate("Widget", "Dec"))
        self.lineEdit_5.setText(_translate("Widget", "Tháng sinh nhật"))
